name: Rust CI

on:
  push:
    branches: [ "main" ]
    paths:
      - "src/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - ".github/workflows/rust_build.yml"
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:


env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
